[phases.install]
cmds = ["npm ci"]
# Forçar uso do Node.js 20
pkgs = ["nodejs_20", "chromium", "fonts-liberation", "libnss3", "libatk1.0-0", "libatk-bridge2.0-0", "libcups2", "libdrm2", "libxkbcommon0", "libxcomposite1", "libxdamage1", "libxrandr2", "mesa-utils", "pango"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
