providers = ["node"]

[variables]
# Previne o servidor (VPS) de estourar a memoria RAM e travar durante o build (OOM)
NODE_OPTIONS = "--max-old-space-size=1536"
NIXPACKS_NODE_VERSION = "20"

# Limita o numero de threads do Next.js para nao usar 1400% de CPU
NEXT_PRIVATE_MAX_WORKERS = "1"

# Reduz overhead do Next.js
NEXT_TELEMETRY_DISABLED = "1"

# Variáveis do Puppeteer
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"

[phases.setup]
nixPkgs = ["...", "chromium"]
aptPkgs = ["fonts-liberation", "libxss1"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
